### PR TITLE
fixed assumption - master

### PR DESCRIPTION
**Pull request by ATypescriptEnjoyer**
Think i pulled wrong branch, was meant to direct towards master for this small change :)

### CODE REVIEW

**Comment by FurkanS1821** [comment]
master branch is our release branch, every change goes into indev.

**Comment by Deudly** [comment]
Don't commit to master. Main repo is Indev

**Comment by ATypescriptEnjoyer** [comment]
I tried to commit to Indev and @Deudly closed it for some reason.

**Comment by FurkanS1821** [comment]
It feels weird to me to open a PR for such small thing too. Just wait for an admin.

**Comment by ATypescriptEnjoyer** [comment]
I just spotted it while reading through, thought it could be changed to be better suited :)

**Comment by moonshadow565** [comment]
When we do reverse engineering  assumptions are n3cessity, should stay like that.
Als0 1 think that creator is male gendered noun so him shuld be corekt here.

**Comment by MythicManiac** [comment]
@JackRyder the PR was valid as far as I can tell, though please adhere to our commit and PR guidelines if you want it to get past. Those can be found from the wiki.

**Pull request closed without merging**
