### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by subramanir2143**
Made some grammatical corrections

### CODE REVIEW

**Review by danil179 — APPROVED** [review]
Thank you! The README.md has also technical errors (like `Settings/GameServerSettings.json`).

Be aware that you need to sign the CLA.

**Comment by lzardy** [comment]
In my opinion the auto installer recommendation should also be removed.

**Comment by MythicManiac** [comment]
I'm just going to flag this as invalid, as this clearly is a very minor contribution intended for easy hacktoberfest progress, and the CLA has not been signed in the 3 days this PR has been open for

**Comment by danil179** [comment]
Closing this due to not signing the CLA. Author should reopen after signing.

**Pull request closed without merging**
