### PR TITLE
dash to dash-fix; rebase is horror

### PR DESCRIPTION
**Pull request by Maufeat**

### CODE REVIEW

**Comment by DeudlyYT** [comment]
GG

**Comment by FurkanS1821** [comment]
4792 files changed? WTF?

**Comment by DeudlyYT** [comment]
I think he deleted files and then created again XD @FurkanS1821

**Comment by MythicManiac** [comment]
Why are there so many files changed? It seems like something is wrong with this PR, you might want to fix it before merging

**Pull request closed without merging**
