### PR TITLE
Adapt the coordinates of the objects on the new summoners rift map

### PR DESCRIPTION
**Pull request by Vidalee**
They are relatively accurate, I'm just unsure about the blue shrine at the fountain (the hp bar appears shifted, maybe it's just because my windows can't move more in that direction?)

### CODE REVIEW

**Comment by danil179** [comment]
If you got the positions by logging position or trial and error these are not perfectly correct. 
The correct positions should be in some of the packets from replays (look at ReplayInspector repository).
Also maybe in game files (minion path surely there, and also some of the positions).

**Comment by moonshadow565** [comment]
The positions can be generated from game files so that would be first place to look.

**Comment by Vidalee** [comment]
Yeah that make more sense, I'll look into them

**Comment by danil179** [comment]
The positions need to be autogenerated from files in Default repo.
We need an automap generator from files instead of file for every map and map loader so Im closing this PR currently.

We can merge this for the meanwhile if conflicts solved.

**Pull request closed without merging**
