### PR TITLE
Fixed champion emotions.

### PR DESCRIPTION
**Pull request by Taimander**
When a champion starts an emotion (Dancing, taunting, joking, etc.) the champion should stop its movement.

The StopChampionMovement method is in ApiFunctionManager so it can be used by other classes, it makes the specified champion stop moving.

In the HandleEmotion class the method HandlePacket was modified so it makes the champion stop using the StopChampionMovement from the ApiFunctionManager.

### CODE REVIEW

**Comment by MythicManiac** [comment]
The diff is likely broken due to `LF` characters being replaced by `CRLF` (windows default behaviour), as these were not uploaded by a git client which handles CRLF to LF conversion.

Please re-push the changes in a way that doesn't change the file endings and I'll give this a proper review, feel free to ask for help regarding this on Discord if you need any :)

**Comment by Taimander** [comment]
Fixed files.
I'm so sorry about that, it was the CR LF format.

**Comment by Taimander** [comment]
Ok, I'm still learning, I fixed other bug with recall but accidentally pushed it, so it commited to my fork, but then I realized that it would be here too, before I can pr the other bug fix, I'll need to finish with this one. Please ignore the extra commits.

**Comment by JoaRiski** [comment]
@Taimander no problem, I'd recommend trying out branches for these kind of situations where you want to edit two different things at once :)

**Comment by MythicManiac** [comment]
@Taimander no problem, I'd recommend trying out branches for these kind of situations where you want to edit two different things at once :)

**Comment by MythicManiac** [comment]
Closing in favor of #687

**Pull request closed without merging**
