### PR TITLE
Packet handlers rework vol. 2

### PR DESCRIPTION
**Pull request by horato**
- Split packet implementations into C2S and S2C packets
- Changed the way C2S packets are parsed
- Made PacketHandlers generic -> removed the byte[] part of the HandlePacket method and replaced it with solid class

### CODE REVIEW

**Comment by MythicManiac** [comment]
This is a welcome proposal, however...

This is kind of difficult to review because there are mass changes / file moves and such, but then there are some small changes made by hand.

It's enormously time consuming to review this line by line. There really isn't a good way to pinpoint what changes were made by some mass refactoring tools and what were by hand either, so it's really difficult to review what actually has changed and what not.

It also seems the original code was not removed, just duplicated into new files. I'm assuming this was intentional.

Overall this is a good idea, but I'd like to request a bit different approach to submitting this PR. If you could, please submit these changes again with the following modifications:

- Submit the mass refactoring by tooling in a singular PR of it's own
    - Omit the `Packets` directory from the directory tree. Instead, just have `PacketHandlers` and `PacketDefinitions`. Or optionally don't omit the `Packets` directory, but rename `PacketHandlers` directory to just `Handlers` and the `PacketDefinitions` to just `Definitions`.
- Submit any handwritten refactoring in a separate PR

Glad to see you back, keep up the good work :+1:

**Comment by horato** [comment]
I don't think there are lots of auto refactoring changes..  The first 2 commits are just merge issues, the actual refactoring is in https://github.com/LeagueSandbox/GameServer/pull/506/commits/2ca73c33eff3c17d87b2242c148354223177dbfd
Basically, I took out C2S parts from S2C packet definitions, gave them baseclass, changed the way those packet classes are initialized and made packet handlers generic so they accept class instance instead of byte array. 
I don't know how to split that into separate PRs

**Comment by MythicManiac** [comment]
Hm, well this is a really big piece to review at once, I'll see what I can do. I'm assuming you have tested this to be working?

**Comment by horato** [comment]
yup

**Comment by MythicManiac** [comment]
It seems like you're duplicating all the code to new classes but not removing the original code, are the new classes actually being used?

**Comment by MythicManiac** [comment]
@moonshadow565 I think you should give your opinion on this one as well since you know more about the packets than I do

**Comment by horato** [comment]
Closing this as it is no longer mergable because of other packet refactoring

**Pull request closed without merging**
