### PR TITLE
API branch (again)

### PR DESCRIPTION
**Pull request by FurkanS1821**
Hope I wont come up with problems again.

### CODE REVIEW

**Comment by MythicManiac** [comment]
Where did the chat command manager code gone?

**Comment by FurkanS1821** [comment]
Deleted, since i cannot fix it

**Comment by MythicManiac** [comment]
Well that's hardly a solution

**Comment by FurkanS1821** [comment]
OK, but i have a little problem

I can't create a branch.

**Comment by MythicManiac** [comment]
You should be able to once you accept the org invitation now

**Pull request closed without merging**
