### PR TITLE
Resolve  #915 Use GetBytes() instead of Marshal.Copy

### LINKED ISSUE #915: Reading ENetCS.Packet should be done through provided interface
https://github.com/LeagueSandbox/GameServer/blob/indev/PacketDefinitions420/PacketHandlerManager.cs#L250

Accessing unamanged data pointer to copy packet data into new byte[] is unecesary when Packet interface provides explicit interface for such purpose.

### PR DESCRIPTION
**Pull request by moonshadow565**

### CODE REVIEW

**Review by danil179 — APPROVED** [review]
It passes build so I think it's OK. (Also checked that GetBytes actually doing the same with a lot more checks)

**Comment by danil179** [comment]
You need to open issue to explain why it is needed and then I'll merge it.

**Review by HarmfulBreeze — APPROVED** [review]
Looks good to me, I checked the ENet code and it does the same, so we'd better use the proper function with added checks.

**Comment by moonshadow565** [comment]
the checks are same because IntPtr Data getter calls same check function

**Pull request merged**
