### PR TITLE
Removed Ninject

### PR DESCRIPTION
**Pull request by eddy5641**
Moved a lot of classes to static to remove the ninject dependancy
Removed ResolveDependency in program.cs
Fixed tests project that broke with the previous pull request

### CODE REVIEW

**Review by eddy5641 — COMMENTED** [review]
Removed Ninject from main LIB
Fixed some errors with the tests class
I forgot to remove Ninject from tests though

**Comment by MythicManiac** [comment]
Mind clarifying a bit as to what pros and cons there are to doing this?

**Comment by eddy5641** [comment]
The use of Ninject in the current state basically creates a static dictionary and call the objects. There is really no pros or cons, except it allows for the removal of an unneeded dependency, as the classes can just be made static instead of using Ninject. This makes it just a little bit easier to determine memory usages, as the classes are exposed, instead of being behind Ninject

**Comment by MythicManiac** [comment]
Converting every class to static seems like the easy way out rather than the right solution, and I can see it causing issues with tests for example. I will elaborate more in a bit and suggest some options. One would be using Ninject properly instead of the way it currently is being used, rather than removing it.

**Comment by MythicManiac** [comment]
As discussed on Discord:

- Removal of Ninject is OK, as it apparently had a big performance impact.
- Instead of making everything static, a better solution would be to have a context holding object that holds instances of them. This could either be the current game object (e.g. `Game.ContentManager`), or alternatively an entirely new `Context` object that holds all of the instances that should be globally accessible. This could be then passed around in place of `Game`

**Pull request closed without merging**
