### PR TITLE
Resolve #904 -- Add LeaguePackets as submodule

### LINKED ISSUE #904: League Packets should Be Imprted as Submodule
This will happen with 2 PRs:

1. Add LeaguePackets as a submodule
2. Use it and remove the NuGet

### PR DESCRIPTION
**Pull request by danil179**
Added LeaguePackets submodule
Removed LeaguePackets NuGet

Resolve #904

### CODE REVIEW

**Comment by danil179** [comment]
Rebuild and debug as LeagueSandbox/LeaguePackets#4 got merged.

**Review by MythicManiac — COMMENTED** [review]
Looks good to me, but it seems there's a conflict. Please resolve that and ping me for a re-check

**Comment by danil179** [comment]
Travis script doesn't have mono. We need to update LeaguePackets to .netcore 3 in order to have successful build.

**Comment by danil179** [comment]
@MythicManiac Conflicts resolved

**Review by FurkanS1821 — APPROVED** [review]

**Pull request merged**
