### PR TITLE
Replace equality checks of floating point numbers with a constant threshold.

### LINKED ISSUE #755: Replace (in)equality checks for floating point numbers with great/lesser than
Equality comparisons on floating point number can become inaccurate due to how they work, it is better to check whether they are below/above/between a threshold

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Veykril` in `#general`.

### PR DESCRIPTION
**Pull request by harrebarre**
Progress #755

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Review by Veykril — DISMISSED** [review]
You forgot to import the Math class cause the travis build fails on finding Math, add a ``using`` directive

**Comment by danil179** [comment]
Tell me if I can close this PR or if you want to solve the conflicts and I'll merge it.

And change Closes to Progress.

**Comment by danil179** [comment]
I have resolved the conflicts, and changed 'Closes' to 'Progress'. Still, Math is not imported.

**Comment by danil179** [comment]
> 
> 
> You forgot to import the Math class cause the travis build fails on finding Math, add a `using` directive

Fixed that. Going to merge this.

**Review by danil179 — APPROVED** [review]
Fixed the conflicts and imports. Ready for merge.

**Pull request merged**
