### PR TITLE
Resolve #504 - GameObjects' namespaces' are wrong

### LINKED ISSUE #504: GameObjects' namespaces' are wrong
This happened after moving them into different folders.

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Furkan_S` in `#game-server`.

### PR DESCRIPTION
**Pull request by chutch1122**
After separating of GameObjects into folders, the individual classes' namespaces' were not updated to reflect the categorization.

This PR adjusts the namespaces of those classes. Note that there is a dependent PR in LeagueSandbox/LeagueSandbox-Default: https://github.com/LeagueSandbox/LeagueSandbox-Default/pull/42

### CODE REVIEW

**Comment by moonshadow565** [comment]
You didn't update script files reference so the build fails, you should update all of them ...

**Comment by chutch1122** [comment]
You mean https://github.com/LeagueSandbox/LeagueSandbox-Default/pull/42?

**Comment by moonshadow565** [comment]
Yeah, i mean those.

**Comment by MythicManiac** [comment]
Yeah, can't be merged before the build succeeds, good work otherwise :+1: 

How about the `Stats` vs. `Statistics`? Usually more verbose is better, but here at least personally I don't think `stats` (even though technically a shorthand for statistics) even means the same thing as `statistics`. Probably due to games usually referring to them as `stats`, thus why I'd think the proper terminology to actually be `stats`. Any other thoughts on this? Was the `Statistics` namespace also derived directly from League?

**Comment by indiemini** [comment]
Re: Statistics vs Stats, I would use Statistics for post-game statistics, ie Champion damage done, gold earned, etc. Statistics are (imo) more akin to something to be graphed, while Stats are HP, MP, etc.

But yeah, if League/Riot have called them Statistics, then it may be worthwhile to stay consistent with their naming.

**Comment by FurkanS1821** [comment]
This was fixed with #571.

**Pull request closed without merging**
