### PR TITLE
Separate packets into files

### PR DESCRIPTION
**Pull request by horato**
+ rename Packet._game to Packet.Game and make it readonly.

nothing else is subject to this PR ;)

### CODE REVIEW

**Comment by horato** [comment]
Split C2S and S2C packets into separate namespaces

**Comment by horato** [comment]
Rebased with indev

**Review by MythicManiac — APPROVED** [review]
Assuming this is tested and working, looks good to me. Can you confirm? @horato 

Good work :+1:

**Comment by horato** [comment]
Yup, nothing actually changed. Resharper took care of that.

**Pull request merged**
