### PR TITLE
Game server app updates

### PR DESCRIPTION
**Pull request by MatthewFrench**
#673 

Completed in this pull request:
- [x] Create GameServerConsole for only the console version(current).
**Create a UI for Game Server App that includes**
- [x] All JSON options as live UI options 
    - [ ] (If server is running, they modify server behavior)
- [x] Add toggle-able logging level display
- [x] Server should be start and stoppable without closing the app
- [x] Should have option at auto-start server on launch and auto-start client on server ready
- [ ] **Add experimental decentralized  developer match making and chat**
    - [ ] Add match making so you can be in your game or join another game from a connected client
    - [ ] Add chat so everyone can talk to each other
    - [ ] Constantly update the connected list and try to expand the network of clients by asking for IPs

screen shot 2018-08-30 at 12 36 32 am

### CODE REVIEW

**Comment by MatthewFrench** [comment]
I'll fix the merge conflicts tomorrow.

**Comment by MythicManiac** [comment]
This is very difficult to review, that's all I'll say for now.

**I do want to review this before merging**, just be prepared that since the PR itself is monolithic the review process might take a very long duration, not to mention the back and forth discussion / fixes.

If there's any way you can submit this in the form of multipe PRs, that would very very much be appreciated. That would also increase the chances of this being merged by a big factor.

**Comment by MythicManiac** [comment]
Every part in this PR that does not build or depend upon other changes in this PR should be in their own respective PRs

**Comment by MythicManiac** [comment]
Otherwise looking good from what I can tell by a glance 👍 , the way this is being added is just making it very hard for me

**Pull request closed without merging**
