### PR TITLE
Resolve #682 -- Added client events API

### LINKED ISSUE #682: API for client events
Add API for client events, all the requests from the client should invoke events like:
```
OnSpawn
```
or 
```
OnBlueTip
```

that way it is easier to create scripts by listen to these events.

### PR DESCRIPTION
**Pull request by danil179**
Resolve #682.

Added most of the events to the Client API, still need to be integrated such that the events will be actually invoked (could be done by switching all the functions to delegates and add events to each one).

### CODE REVIEW

**Review by MythicManiac — COMMENTED** [review]
Looks good to me, but I'd like to wait for @moonshadow565 to comment on this as he should be more up to date on this section than I am.

**Comment by moonshadow565** [comment]
I think it would be better to modify already existing interface than start with a new one:
https://github.com/LeagueSandbox/GameServer/blob/indev/GameServerCore/Packets/Interfaces/IPacketReader.cs#L5

**Comment by danil179** [comment]
This is not exactly the same, IPsacketReader is for the bridge itself to read packets, also IPacketReader is not really good interface cause all the functions are RequestType ReadRequest(byte[]), so I prefer not to modify it, cause that will cause changing on all the files that uses it.

see my issue #696 that desribes how the system should work.

**Comment by horato** [comment]
How do you plan to use this interface?
Is it really ok to merge single unused interface? Even more so when it misses the actual types and is faked with int?

**Comment by danil179** [comment]
yes, cause this is one important step to achieve the full integration, see #696 on how I plan to use it.

**Comment by horato** [comment]
I am more interrested in low-level description.
By unused I mean no reference to it. I get the idea, but I miss the point of adding single interface without any usage.

Also, DI implementation is long time run atm.

**Comment by danil179** [comment]
I dont know why do you think DI is long time run, I heard about the NInject problems but that seems to me unrelated, this DI not really using any library, it's just simple use of polymorphism.

Currently it is unused, because it is change in the API, the full integration (that will take more time, cause you need to change a lot in the structure of the project) will add the implementations, this interface contains all client events, and will be implemented later (when we integrate moon's packets).

the low-level description is like this (flow scenario):
socket get data -> something with enet happens in the bridge -> reader parsing the packet using PacketDefinitions dll/files -> bridge raise an event using implementation of this interface (IClientAPI) -> now, because the server already have reference to this interface (using the DI as I described in #696 ) and it already add listeners (event handlers), the server easily get all the data to the correct classes, and no need at all to know about how the packet structured.
By using the DI you can easily switch between different versions (just change the PacketDefinitions, if you need a new event you just add it to the API, and not implement it in the bridge).

the same happens in the reverse way so the server inform the bridge about events, and the bridge sends the packets.

This PR is one step in this integration.

We should add also:
IServerAPI (change the notifier and add new events)
The bridge (this is sort of currently part of the App I think) - maybe we should call it ServerNetwork
IServer (this is general interface that you create in the bridge to start the server, that should include functions like GetServerAPI, GetServerVersion, GetServer, Start, Shutdown, etc)

Also all the types already in moon's packet definitions, after integration of these to the API you could remove the 'using'.

**Comment by horato** [comment]
By dependency injection I though you mean using an IoC container, which is troublesome because of the current circular dependencies.

This seems to take the idea of switchable packet definitions to a whole new level. 

I don't like the idea of classic c# events because of the lack of weak references, but that's discussion to another time and place.

**Review by horato — APPROVED** [review]

**Review by horato — CHANGES_REQUESTED** [review]
On second look, please use keywords instead of types (Int32 to int, String to string, etc..)

**Comment by MythicManiac** [comment]
@horato as far as I'm concerned, I much prefer multiple small PRs over a huge monolithic PR (such as #699)

But as for the implementation, we do have a big need for a way to pre-define what way to implement big features / changes. Specifications.

**Comment by danil179** [comment]
Don't merge this PR yet, The current systems of requests should be integrated instead of functions signatures, Im updating the issues to match the new design that I proposed, and later Ill open a new PR about the changes.

**Comment by danil179** [comment]
Closed, new PRs will update the requests instead.

**Pull request closed without merging**
