### PR TITLE
Migrate to new csproj format

### PR DESCRIPTION
**Pull request by pipe01**

### CODE REVIEW

**Comment by danil179** [comment]
Travis fail on build. I don't know much about this new format, but it seems to me that you removed all the files from compilation.

The main problem with Travis is creating/accessing folders. (Which I think should be fixed at the repo level)

**Comment by lzardy** [comment]
> Travis fail on build. I don't know much about this new format, but it seems to me that you removed all the files from compilation.

Manual build works fine for me.

**Comment by pipe01** [comment]
Yeah I have no idea how to fix it.

> it seems to me that you removed all the files from compilation.

That's because the new csproj format includes all files by default so there's no need to specify them one by one.

**Comment by danil179** [comment]
You have problem with creating folders:
```
warning MSB3191: Unable to create directory "obj/Debug/net462/". Access to the path "/home/travis/build/LeagueSandbox/GameServer/GameMaths/obj/Debug" is denied. [/home/travis/build/LeagueSandbox/GameServer/GameMaths/GameMaths.csproj]
```

Try to figure out what is the paths that exist for Travis. (the old paths)

**Comment by reidwil** [comment]
ok

**Comment by danil179** [comment]
When I test it (after resolving conflicts), I get that 'libenet' cannot be found exception.

**Comment by danil179** [comment]
@pipe01 Have you been able to run this with this runtime error? It seems that I'm unable to get rid of this 'libenet' DLL not found error.

EDIT: I was able to solve the problem with travis using `sudo` (always solve problems, should be the default)

**Review by danil179 — CHANGES_REQUESTED** [review]
See #906 for some errors and add the `sudo` solution.

**Comment by danil179** [comment]
Close this in favor of #906

**Pull request closed without merging**
