### PR TITLE
Added generic NetworkHandler and new types

### PR DESCRIPTION
**Pull request by danil179**
Progress #696 

Implemented the generic handler and some types.

Next step will be to make all packets to implement IPacket interface (or wrap them with new class that implements it).

### CODE REVIEW

**Review by MythicManiac — DISMISSED** [review]
Looks good to me 👍

It seems like there's a merge conflict, that needs to be resolved before merging.

While you're at it, please squash the commits together and follow [the commit format guidelines](https://github.com/LeagueSandbox/GameServer/wiki/4.07.-Committing) so I don't have to squash merge and do that manually.

**Comment by danil179** [comment]
Solved the merge conflict, I had a problem to squash and merge, if I merge first I get a problem when trying to squash, if I squash first then I need to resolve the conflicts with some commit after that so I end up with 2 commits, not sure how I can do this with only single commit.

**Comment by MythicManiac** [comment]
And the conflict is back

**Comment by danil179** [comment]
Solved the conflict.

**Review by Veykril — APPROVED** [review]

**Pull request merged**
