### PR TITLE
Progress #755

### LINKED ISSUE #755: Replace (in)equality checks for floating point numbers with great/lesser than
Equality comparisons on floating point number can become inaccurate due to how they work, it is better to check whether they are below/above/between a threshold

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Veykril` in `#general`.

### PR DESCRIPTION
**Pull request by rexiaxm7**

### CODE REVIEW

**Comment by danil179** [comment]
Im not sure that this is the only place with equality operator on float numbers, but this is certainly progress.

So maybe change commit and title to Progress #755

**Comment by rexiaxm7** [comment]
I fixed only equality comparisons for the position.

According to my survey 5 classes have the floating point equality comparisons.
5 classes are ...
・GameMaths\Geometry\Clipper.cs
・GameServerLib\API\UnitCrowdControl.cs
・GameServerLib\GameObjects\GameObject.cs
・GameServerLib\GameObjects\Spells\Buff.cs
・GameServerLib\GameObjects\Stats\StatModifier.cs

But Clipper.cs is Library. Isn't it nessesary to cover this?

**Comment by danil179** [comment]
Don't cover/change Clipper.cs (no one knows what is actually happens there).

Seems like 4 classes changes got deleted or something, what I suggest is copy-paste https://github.com/LeagueSandbox/GameServer/pull/776/files
https://github.com/LeagueSandbox/GameServer/pull/769/files
https://github.com/LeagueSandbox/GameServer/pull/768/files


Just make one constant EPSILON (and don't use C# defined ones) and don't multiply it by any constant.

Ping me and Ill review&merge it after the PR got progress, you can also solve the conflict with what you already fixed and I'll review&merge it.

**Comment by danil179** [comment]
Outdated.

The changes already got merged it another PR. (and the other ones are from deleted functions)

**Pull request closed without merging**
