### PR TITLE
Use 'using static' for ApiFunctionManager function calls

### PR DESCRIPTION
**Pull request by Zaksh**
Resolves https://github.com/LeagueSandbox/GameServer/issues/739

### CODE REVIEW

**Comment by MythicManiac** [comment]
I'm fairly sure that issue is in the wrong repository, and was actually intended for https://github.com/LeagueSandbox/LeagueSandbox-Default

@Pokemonred200 can you comment on this, seeing as you created the issue?

**Comment by yasinallahdev** [comment]
@MythicManiac Issue was intended primarily for scripts, though I made it here for consistency's sake since several constructors reference ApiFunctionManager on GameServer as well.

**Comment by MythicManiac** [comment]
Alright. So summed up:
The pull request is valid and addresses the issue, but the issue was lacking in description. I will close this PR but won't mark it as invalid, so you can keep that hacktoberfest contribution.

**Comment by Zaksh** [comment]
> 
> 
> Alright. So summed up:
> The pull request is valid and addresses the issue, but the issue was lacking in description. I will close this PR but won't mark it as invalid, so you can keep that hacktoberfest contribution.

Thank you 😄

**Pull request closed without merging**
